version: "3.5"

x-shared-config:
  app_image_name: &app_image_name
    image: mutations/node:16.17.0-alpine3.16-2022-09-14

  app_base: &app_base
    <<: *app_image_name
    env_file:
      - .env
      - .env.local
    environment:
      - HISTFILE=/app/log/.bash_history
      - NODE_ENV=${NODE_ENV:-development}
    stdin_open: true
    tty: true
    tmpfs:
      - /tmp
    user: "1069:1420"
    volumes:
      - .:/app:cached
    working_dir: /app

services:
  app:
    <<: *app_base
    # FIXME: update command after dev environment
    # command: local-dev
    entrypoint: npm
    ports:
      - 3000:3000
      - 3001:3001
    tmpfs:
      - /tmp:exec,mode=755
